"""
config.py — Central configuration for the Redrob Candidate Ranking System.

All weights, thresholds, skill taxonomies, and company classifications live here.
Changing a weight here changes the entire system's behavior — no magic numbers elsewhere.
"""

import os
from pathlib import Path

# ============================================================================
# Paths
# ============================================================================
PROJECT_ROOT = Path(__file__).parent.resolve()
DATA_DIR = PROJECT_ROOT / "data"
CHALLENGE_DIR = PROJECT_ROOT / "India_runs_data_and_ai_challenge"
CANDIDATES_FILE = CHALLENGE_DIR / "candidates.jsonl"
SAMPLE_CANDIDATES_FILE = CHALLENGE_DIR / "sample_candidates.json"

# Pre-computed artifact paths (generated by precompute.py on Kaggle)
CANDIDATE_EMBEDDINGS_FILE = DATA_DIR / "candidate_embeddings.npz"
JD_EMBEDDINGS_FILE = DATA_DIR / "jd_embeddings.npz"
CANDIDATE_FEATURES_FILE = DATA_DIR / "candidate_features.parquet"
XGBOOST_MODEL_FILE = DATA_DIR / "xgb_ranker.json"
CANDIDATE_INDEX_FILE = DATA_DIR / "candidate_index.json"

# Embedding model (used during pre-computation on Kaggle)
EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIM = 384

# ============================================================================
# Composite Score Weights
# ============================================================================
WEIGHTS = {
    "skills_match": 0.25,
    "career_trajectory": 0.30,
    "semantic_similarity": 0.15,
    "experience_fit": 0.10,
    "location_fit": 0.05,
    "education_fit": 0.05,
    "anti_pattern_penalty": 0.10,  # subtracted
}

# ============================================================================
# JD-Specific: Skills Taxonomy
# ============================================================================

# Skills that the JD EXPLICITLY requires (must-have)
MUST_HAVE_SKILLS = {
    # Embeddings & retrieval
    "sentence-transformers", "sentence transformers", "openai embeddings",
    "bge", "e5", "embeddings", "embedding", "text embeddings",
    "semantic search", "dense retrieval", "vector search",
    "retrieval", "information retrieval", "search systems",
    # Vector databases & hybrid search
    "pinecone", "weaviate", "qdrant", "milvus", "opensearch",
    "elasticsearch", "elastic search", "faiss", "annoy",
    "vector database", "vector db", "hybrid search",
    # Python
    "python",
    # Evaluation & ranking
    "ndcg", "mrr", "map", "ranking", "ranking systems",
    "evaluation", "a/b testing", "ab testing",
    "recommendation systems", "recommendation engine", "recommendations",
    "search ranking", "learning to rank", "ltr",
    # NLP / IR core
    "nlp", "natural language processing", "information retrieval",
    "text mining", "text processing",
    # Production ML
    "machine learning", "ml", "deep learning", "dl",
    "pytorch", "tensorflow", "transformers", "huggingface",
    "model deployment", "ml ops", "mlops", "model serving",
}

# Skills the JD says are nice-to-have
NICE_TO_HAVE_SKILLS = {
    "lora", "qlora", "peft", "fine-tuning", "fine tuning",
    "fine-tuning llms", "llm fine-tuning",
    "xgboost", "lightgbm", "catboost", "gradient boosting",
    "neural ranking", "cross-encoder", "bi-encoder",
    "distributed systems", "kubernetes", "docker", "kafka",
    "large-scale inference", "inference optimization",
    "rag", "retrieval augmented generation",
    "langchain", "llamaindex", "llama index",
    "prompt engineering", "llm", "large language models",
    "gpt", "claude", "gemini",
    "open source", "open-source contributions",
    "hr tech", "recruiting tech", "marketplace",
}

# Skills indicating CV/speech/robotics focus (JD explicitly says NO)
ANTI_SKILLS = {
    "computer vision", "cv", "image classification", "object detection",
    "image segmentation", "yolo", "opencv", "image processing",
    "speech recognition", "speech synthesis", "tts", "asr",
    "text to speech", "speech to text", "voice recognition",
    "robotics", "ros", "robot operating system", "slam",
    "autonomous driving", "self-driving", "lidar",
    "gans", "generative adversarial", "stable diffusion",
    "midjourney", "dalle", "image generation",
}

# Non-technical skills (signal that candidate may not be technical)
NON_TECHNICAL_SKILLS = {
    "project management", "scrum", "agile", "jira",
    "six sigma", "lean", "pmp", "prince2",
    "accounting", "financial analysis", "bookkeeping",
    "photoshop", "illustrator", "canva", "figma",
    "content writing", "copywriting", "seo",
    "sales", "business development", "crm",
    "human resources", "recruitment", "talent acquisition",
    "marketing", "digital marketing", "social media marketing",
    "supply chain", "logistics", "inventory management",
    "autocad", "solidworks", "creo", "catia", "ansys",
    "civil engineering", "structural engineering",
    "mechanical engineering", "electrical engineering",
}

# ============================================================================
# JD-Specific: Company Classification
# ============================================================================

# IT Services / Consulting firms — the JD explicitly rejects candidates
# whose ENTIRE career has been at these companies.
CONSULTING_FIRMS = {
    "tcs", "tata consultancy services", "tata consultancy",
    "infosys", "wipro", "accenture", "cognizant",
    "capgemini", "hcl", "hcl technologies",
    "tech mahindra", "mindtree", "ltimindtree", "lti",
    "mphasis", "hexaware", "cyient", "persistent systems",
    "zensar", "sonata software", "coforge", "niit technologies",
    "l&t infotech", "lt infotech", "larsen & toubro infotech",
    "cts", "dxc technology", "dxc", "atos",
    "deloitte", "kpmg", "ey", "pwc", "ernst & young",
    "ibm consulting", "ibm global services",
}

# Fictional/test companies in the dataset
FICTIONAL_COMPANIES = {
    "dunder mifflin", "stark industries", "wayne enterprises",
    "pied piper", "initech", "acme corp", "globex inc",
    "hooli", "umbrella corp", "cyberdyne", "weyland-yutani",
    "oscorp", "lexcorp", "tyrell corp",
}

# Known product companies (positive signal)
PRODUCT_COMPANIES = {
    "google", "meta", "facebook", "amazon", "microsoft", "apple",
    "netflix", "uber", "airbnb", "stripe", "spotify", "twitter",
    "flipkart", "razorpay", "swiggy", "zomato", "cred",
    "phonepe", "paytm", "ola", "meesho", "groww", "zerodha",
    "freshworks", "zoho", "postman", "browserstack", "hasura",
    "atlassian", "salesforce", "shopify", "datadog", "snowflake",
    "databricks", "confluent", "elastic", "mongodb",
    "hugging face", "huggingface", "openai", "anthropic",
    "deepmind", "cohere", "stability ai",
    "linkedin", "indeed", "glassdoor",  # recruiting tech
}

# ============================================================================
# JD-Specific: Role / Title Classification
# ============================================================================

# Titles that are clearly relevant to the JD
RELEVANT_TITLES = {
    "ai engineer", "senior ai engineer", "staff ai engineer",
    "ml engineer", "machine learning engineer", "senior ml engineer",
    "data scientist", "senior data scientist", "staff data scientist",
    "applied scientist", "research scientist", "research engineer",
    "nlp engineer", "search engineer", "ranking engineer",
    "recommendation engineer", "relevance engineer",
    "software engineer", "senior software engineer", "staff engineer",
    "backend engineer", "platform engineer",
    "data engineer", "senior data engineer",
    "tech lead", "engineering manager",
    "full stack engineer", "full-stack engineer",
    "deep learning engineer", "computer scientist",
}

# Titles that are clearly NOT relevant (hard reject unless career shows pivot)
IRRELEVANT_TITLES = {
    "accountant", "senior accountant", "chartered accountant",
    "hr manager", "human resources manager", "recruiter",
    "marketing manager", "digital marketing manager",
    "sales executive", "sales manager", "business development",
    "content writer", "copywriter", "content strategist",
    "graphic designer", "ui designer", "ux designer",
    "civil engineer", "mechanical engineer", "electrical engineer",
    "chemical engineer", "structural engineer",
    "operations manager", "supply chain manager",
    "financial analyst", "investment analyst",
    "customer support", "customer success",
    "teacher", "professor", "lecturer",
    "doctor", "physician", "nurse",
    "lawyer", "advocate", "legal counsel",
}

# ============================================================================
# JD-Specific: Location Scoring
# ============================================================================
LOCATION_SCORES = {
    # Preferred locations (JD says Pune/Noida)
    "pune": 1.0,
    "noida": 1.0,
    # Acceptable Indian cities
    "hyderabad": 0.90,
    "bangalore": 0.90,
    "bengaluru": 0.90,
    "mumbai": 0.85,
    "delhi": 0.85,
    "new delhi": 0.85,
    "gurgaon": 0.85,
    "gurugram": 0.85,
    "delhi ncr": 0.85,
    "chennai": 0.75,
    "kolkata": 0.70,
}
DEFAULT_INDIA_LOCATION_SCORE = 0.65
DEFAULT_NON_INDIA_LOCATION_SCORE = 0.30

# ============================================================================
# Experience Scoring
# ============================================================================
EXPERIENCE_IDEAL_CENTER = 7.0    # Sweet spot: 6-8 years
EXPERIENCE_SIGMA = 3.0           # Gaussian spread
EXPERIENCE_HARD_MIN = 2.0        # Below this: likely too junior
EXPERIENCE_HARD_MAX = 20.0       # Above this: likely overqualified

# ============================================================================
# Behavioral Signal Weights & Thresholds
# ============================================================================
BEHAVIORAL = {
    # last_active_date: days since last active
    "inactive_heavy_penalty_days": 180,    # >6 months = heavy penalty
    "inactive_moderate_penalty_days": 90,  # >3 months = moderate penalty
    "inactive_decay_rate": 0.005,          # exponential decay per day

    # open_to_work_flag
    "not_open_to_work_multiplier": 0.70,

    # recruiter_response_rate
    "response_rate_high": 0.60,            # above this = boost
    "response_rate_low": 0.20,             # below this = penalty
    "response_rate_boost": 1.10,
    "response_rate_penalty": 0.75,

    # avg_response_time_hours
    "slow_response_hours": 168,            # 1 week
    "slow_response_penalty": 0.85,

    # interview_completion_rate
    "low_interview_completion": 0.50,
    "low_interview_penalty": 0.85,

    # notice_period_days
    "ideal_notice_days": 30,
    "long_notice_days": 90,
    "long_notice_penalty": 0.90,
    "very_long_notice_penalty": 0.80,

    # github_activity_score
    "github_high": 50,
    "github_boost": 1.05,
    "github_no_account": -1,              # -1 means no GitHub linked

    # profile_completeness_score
    "low_completeness": 50,
    "low_completeness_penalty": 0.90,

    # Verification signals
    "unverified_penalty": 0.95,
}

# ============================================================================
# Honeypot Detection Thresholds
# ============================================================================
HONEYPOT = {
    # Experience-tenure mismatch: claimed experience vs. sum of career durations
    "experience_tenure_ratio_threshold": 2.0,   # if claimed_yrs / actual_yrs > 2.0

    # Skill inflation: too many "expert" skills with short duration
    "max_expert_skills_short_duration": 5,       # more than 5 expert skills with <12mo
    "short_duration_months": 12,

    # Assessment paradox: expert skills but terrible assessment scores
    "expert_with_low_assessment_threshold": 30,  # assessment <30 but claims expert

    # Endorsement anomaly: too many endorsements, zero substance
    "suspicious_endorsement_count": 40,

    # Impossible timeline markers
    "min_career_gap_for_flag": 36,  # months - gap too large

    # Overall honeypot confidence threshold
    "flag_threshold": 3,  # need 3+ red flags to classify as honeypot
}

# ============================================================================
# Anti-Pattern Detection
# ============================================================================
ANTI_PATTERNS = {
    # Title chaser: average tenure < 18 months across 3+ jobs
    "title_chaser_avg_tenure_months": 18,
    "title_chaser_min_jobs": 3,

    # Pure researcher: keywords in descriptions indicating no production work
    "research_only_keywords": [
        "published papers", "research only", "academic lab",
        "phd thesis", "dissertation", "theoretical",
        "no production", "proof of concept only",
    ],

    # No recent code: current role is management/architecture only
    "no_code_titles": [
        "director", "vp", "vice president", "cto", "cio",
        "chief technology", "head of", "general manager",
    ],
}

# ============================================================================
# Career Description Keywords (for semantic feature extraction)
# ============================================================================
CAREER_POSITIVE_KEYWORDS = {
    # Search / retrieval / ranking
    "search system", "search engine", "ranking system", "ranking model",
    "recommendation system", "recommendation engine", "recommender",
    "retrieval system", "information retrieval", "search relevance",
    "candidate ranking", "result ranking", "re-ranking", "reranking",
    "personalization", "content discovery",
    # Embeddings / vectors
    "embedding", "vector search", "vector database", "similarity search",
    "semantic search", "dense retrieval", "approximate nearest neighbor",
    "ann", "knn",
    # Production ML
    "production", "deployed", "shipped", "real users",
    "a/b test", "ab test", "experiment", "online evaluation",
    "model serving", "inference", "latency", "throughput",
    "feature store", "ml pipeline", "training pipeline",
    # NLP specific
    "nlp", "natural language", "text classification",
    "named entity", "sentiment", "tokeniz", "transformer",
    # Scale
    "at scale", "large-scale", "millions of", "billions of",
    "high throughput", "low latency", "distributed",
}

CAREER_NEGATIVE_KEYWORDS = {
    # Pure consulting/services descriptions
    "client requirement", "client deliverable", "onsite coordinator",
    "vendor management", "resource allocation", "bench management",
    # Non-technical
    "sales target", "revenue target", "marketing campaign",
    "brand management", "content calendar", "editorial",
    "financial reporting", "audit", "compliance",
    "customer complaint", "ticket resolution",
    # Pure research without production
    "theoretical framework", "mathematical proof",
    "no deployment", "prototype only",
}

# ============================================================================
# Output Configuration
# ============================================================================
TOP_K = 100  # Number of candidates to output
OUTPUT_PRECISION = 4  # Decimal places for scores
